package com.Dhruv.EducationalPlatform.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.*;

import java.util.Date;

@Data
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

@DynamoDBTable(tableName = "AnswerTable")
public class AnswerEntity {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "discussionId-index" , attributeName = "discussionId")
    @DynamoDBAttribute(attributeName = "discussionId")
    private String discussionId;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "userId-index",attributeName = "userId")
    @DynamoDBAttribute(attributeName = "userId")
    private String userId;

    @DynamoDBAttribute(attributeName = "message")
    private String message;

//    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss")
//    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = "createdAt")
    private Date createdAt;
}
