package com.Dhruv.EducationalPlatform.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.*;

import java.util.Date;

@Data
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

@DynamoDBTable(tableName = "CourseTable")
public class CourseEntity {
    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "title")
    private String title;

    @DynamoDBAttribute(attributeName = "description")
    private String description;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "instructorId-index",attributeName = "instructorId")
    @DynamoDBAttribute(attributeName = "instructorId")
    private String instructorId;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss")
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = "createdAt")
    private Date createdAt=new Date();
}
