package com.Dhruv.EducationalPlatform.Entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.*;

import java.util.Date;

@Data
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor

@DynamoDBTable(tableName = "UserTable")
public class UserEntity {


    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "password")
    private String password;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "email-index", attributeName = "email")
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "role-email-index", attributeName = "email")
    @DynamoDBAttribute(attributeName = "email")
    private String email;

    @DynamoDBIndexHashKey(globalSecondaryIndexName = "role-email-index",attributeName = "role")
    @DynamoDBAttribute(attributeName = "role")
    private String role;

    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd hh:mm:ss")
    @DynamoDBTypeConvertedTimestamp
    @DynamoDBAttribute(attributeName = "createdAt")
    private Date createdAt;
}
